### ISSUE TITLE
gulp task babelIt not work

### ISSUE THREAD

**Issue by MingXingTeam** [JesterXL/gulp-basics#1]
hello, I watch your video on youtube.[This link](https://www.youtube.com/watch?v=Mo2xqBPbnlQ&list=PLw5h0DiJ-9PAzyptHOV5-sZ6JIsBJjTcD)

i just do what you had teached.But when i run "gulp babelIt", the result is not correct.it looks like the js not babel success:

![1](https://cloud.githubusercontent.com/assets/4523625/12016934/b0b99ecc-ad8b-11e5-8c7f-a869920d569d.png)

This is my gulpfile.js：

![1](https://cloud.githubusercontent.com/assets/4523625/12016869/2a72c816-ad8b-11e5-9f08-30d3ae2ed355.png)

This is my direcotry:

![1](https://cloud.githubusercontent.com/assets/4523625/12016893/62be4d30-ad8b-11e5-9817-04238a7babde.png)

do you know what's the problem?  thanks for answer. 

best regards!

**Comment by MingXingTeam** [comment]
i add this:--presets es2015.Then it works

**Comment by JesterXL** [comment]
Sorry chief, a lot has changed in the compiler since I published that video, but thanks for posting the answer since I didn't know!
